### ISSUE TITLE
Core Functionality Problems and Fixes

### ISSUE THREAD

**Issue by dhextras** [Hamza12700/drash#3]
1. **Build Directory Missing**

   * You have to manually create the build directory; otherwise, `ld` fails and doesn't create it. You’ll see an error like this:

     ```
     /usr/bin/ld: cannot open output file ./build/debug: No such file or directory
     ```
   * It would be nice if Drash automatically made the build directory when it’s not found.

2. **Compilation Warnings**

   * There are some warnings during compilation. They seem related to unused return values or something like that. Not a big deal, just thought I'd mention it.
  
![Image](https://github.com/user-attachments/assets/7db46d98-7f08-4e0b-b792-3afcf231e75a)

3. **Incorrect Size Formatting**

   * Love that you’re formatting the size, but it’s kind of broken. It shows the units like MB or KB, but the actual size is just in bytes. Not sure if this is on purpose or just slipped through.
   ![Image](https://github.com/user-attachments/assets/dbafefd4-5d4a-4045-bc73-3ab87bb4f049)

4. **Can't Remove Files or Dirs with the Same Name**

   * This one’s pretty bad. You can't remove a file or directory if they have the same name, even if they're in different paths.
   * Example: If I have `src/example` as a file and `src/example` as a folder in different directories, Drash just refuses to delete either one because of the name clash.
   * Maybe generate some kind of ID or use a unique identifier when storing them, and also make sure that the restore process doesn't just depend on the name alone.
   ![Image](https://github.com/user-attachments/assets/e371c045-212a-4bde-9a5e-6742968db449)

5. **Restore Doesn’t Create Missing Directories**

   * If you have something like `src/util/some.c` in Drash, and you delete the `util` directory, restoring `some.c` just fails. Drash should create the missing directories automatically.
   ![Image](https://github.com/user-attachments/assets/1a3c5049-195f-4139-8aa6-33ef6aa905b7)

6. **Cross-Link Device Handling Issue**

   * Drash doesn’t handle cross-device file deletion well (like deleting a file from WSL that's on a mounted Windows drive). It tries to move the file and gives an error, but still creates metadata for it.
   * That breaks the `drash list` command because it shows metadata for a file that doesn't exist anymore. If Drash fails to move the file, it should clean up any related metadata so the list doesn’t break.
   * Also, it would be cool if Drash warned that the file will be permanently deleted instead of just failing. Like how other tools handle cross-device deletes—ask for confirmation and make it clear the file won't be saved.
   ![Image](https://github.com/user-attachments/assets/085eb764-e829-4e26-b25c-bb471df9da77)

**Comment by Hamza12700** [comment]
- Build Directory Missing
> I explain this in the `readme` that the `Makefile` is setup for my development workflow, before building the project checkout the makefile and tweak however you like it.

- Compilation Warnings
> That's wired, I don't get any warning when I compile in debug and release. Regardless, it doesn't matter that much.

- Incorrect Size Formatting
> Now that is a bug, I forgot to update the size to the correct format. Will fix this ASAP.

- Can't Remove Files or Dirs with the Same Name
> Yes, this was on my todo list but forgot. I will fix this issue.

- Restore Doesn’t Create Missing Directories
> Well, it doesn't seem right that `drash` should create the missing directories automatically. It should inform the user that the path of the original file doesn't exists, would you like to create it or provide a new path. This behavior seems more reasonable.

- Cross-Link Device Handling Issue
> That is a wired one. This same error also happens on Linux if you would try to remove something from `/dev/shm` it gives you the same error. I don't know about Windows or WSL but I think on Linux this error happens because the file isn't on the same parition as `/home` or different filesystems.

**Comment by dhextras** [comment]
@Hamza12700 

> Well, it doesn't seem right that `drash` should create the missing directories automatically. It should inform the user that the path of the original file doesn't exists, would you like to create it or provide a new path. This behavior seems more reasonable.

Yes i agree but take care of it rather then just saying the file doesn't exists

> That is a wired one. This same error also happens on Linux if you would try to remove something from /dev/shm it gives you the same error. I don't know about Windows or WSL but I think on Linux this error happens because the file isn't on the same parition as /home or different filesystems. 

Yes basically it doesn't remove files on different file system - Its the correct behaviour because we don't want to store the file on the bin of different filesystems, but just erroring out is doesn't seems to be a good option - like i suggested having a confirmation for permanent deletion is a good suggestion

Regardless, the issue was not that it was when deletion failed - it still creates meta data that makes `drash list` command fail - that's what needs fixing

**Comment by Hamza12700** [comment]
All the bugs are fixed in this [commit](https://github.com/Hamza12700/drash/commit/416bc92fa457bd6b1c04035a0a0528b142bf982b) and the rest are feature requests which I will implement later, so this issue is now closed.

**Comment by dhextras** [comment]
@Hamza12700 

Yes, the fix is working correctly as expected, but just wanted to confirm, the below two are regarded as either todo/feature am I right or you forgot to fix them?

> Can't Remove Files or Dirs with the Same Name

> Well, it doesn't seem right that drash should create the missing directories automatically. It should inform the user that the path of the original file doesn't exists, would you like to create it or provide a new path. This behavior seems more reasonable.

As for the second one, drash should at least show which folder/file is missing rather then saying no such file or directory 

![Image](https://github.com/user-attachments/assets/b499b1be-f8da-4025-b824-1bb07af132b5)
